### PR TITLE
refs#21327 edw_maps module

### PR DESCRIPTION
**Pull request by iuga-paula**

### CODE REVIEW

**Comment by cristiroma** [comment]
@iuga-paula maybe this needs to get removed and this should be pointing to https://www.drupal.org/project/unep_maps ?

**Comment by iuga-paula** [comment]
> @iuga-paula maybe this needs to get removed and this should be pointing to https://www.drupal.org/project/unep_maps ?

@cristiroma not yet, this is currently used on planetGold.

**Comment by iuga-paula** [comment]
I will close this PR after https://helpdesk.eaudeweb.ro/issues/27767 is deployed.

**Comment by iuga-paula** [comment]
The version of the map module has been changed on planetgold: https://helpdesk.eaudeweb.ro/issues/27767#change-144250
https://test.planetgold.org/

**Pull request closed without merging**
